### ISSUE TITLE
Add NYC protobuf extensions

### ISSUE THREAD

**Issue by jprobinson** [brnstz/bus#38]
Not sure if you've pulled these in already, but you can import them to add a few NYC-specific fields to the generic GTFS spec:

http://datamine.mta.info/sites/all/files/pdfs/nyct-subway.proto.txt

Already generated here if you want to copy: https://godoc.org/github.com/jprobinson/gtfs/nyct_subway_proto

Also, example of use: https://github.com/jprobinson/gosubway/blob/master/subway.go#L12-L13

**Comment by jprobinson** [comment]
Doh! Meant for this to be on you're other related project that has train data. You get the idea tho ;)

**Comment by brnstz** [comment]
Cool, I didn't know about these. Will pull it in if I need the info! Thanks.

**Comment by brnstz** [comment]
It happened! @jprobinson 

https://github.com/brnstz/bus/blob/master/internal/partners/mta_nyct_subway.go#L77-L100

**Comment by jprobinson** [comment]
:tada: nice!
